/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Asistencia struct {

	IdAsistencia int32 `json:"id_asistencia,omitempty"`

	IdMatricula int32 `json:"id_matricula"`

	Fecha string `json:"fecha"`

	Estado string `json:"estado"`

	Observaciones string `json:"observaciones,omitempty"`

	FechaRegistro time.Time `json:"fecha_registro,omitempty"`
}
