/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ObservacionComportamiento struct {

	IdObservacion int32 `json:"id_observacion,omitempty"`

	IdMatricula int32 `json:"id_matricula"`

	IdDocenteObservador int32 `json:"id_docente_observador"`

	IdCargaAcademica int32 `json:"id_carga_academica,omitempty"`

	FechaHora time.Time `json:"fecha_hora,omitempty"`

	Descripcion string `json:"descripcion"`

	TipoObservacion string `json:"tipo_observacion,omitempty"`

	AccionesTomadas string `json:"acciones_tomadas,omitempty"`
}
