/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Rol struct {

	IdRol int32 `json:"id_rol,omitempty"`

	Nombre string `json:"nombre"`

	Descripcion string `json:"descripcion,omitempty"`

	EsRolSistema bool `json:"es_rol_sistema,omitempty"`
}
