/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Evaluacion struct {

	IdEvaluacion int32 `json:"id_evaluacion,omitempty"`

	IdCargaAcademica int32 `json:"id_carga_academica"`

	IdPeriodo int32 `json:"id_periodo"`

	IdTipoEvaluacion int32 `json:"id_tipo_evaluacion"`

	IdLogro int32 `json:"id_logro,omitempty"`

	Nombre string `json:"nombre"`

	Descripcion string `json:"descripcion,omitempty"`

	FechaPresentacion string `json:"fecha_presentacion,omitempty"`
}
