/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Acudiente struct {

	IdAcudiente int32 `json:"id_acudiente,omitempty"`

	Nombres string `json:"nombres"`

	Apellidos string `json:"apellidos"`

	DocumentoIdentidad string `json:"documento_identidad"`

	TipoDocumento string `json:"tipo_documento"`

	Telefono string `json:"telefono"`

	Direccion string `json:"direccion,omitempty"`

	CorreoElectronico string `json:"correo_electronico,omitempty"`
}
