/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ArchivoDigital struct {

	IdArchivo int32 `json:"id_archivo,omitempty"`

	TipoArchivo string `json:"tipo_archivo"`

	NombreArchivo string `json:"nombre_archivo"`

	RutaAlmacenamiento string `json:"ruta_almacenamiento"`

	MimeType string `json:"mime_type"`

	FechaCarga time.Time `json:"fecha_carga,omitempty"`

	IdUsuarioCarga int32 `json:"id_usuario_carga,omitempty"`

	EntidadRelacionada string `json:"entidad_relacionada"`

	IdEntidad int32 `json:"id_entidad"`
}
