/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Grupo struct {

	IdGrupo int32 `json:"id_grupo,omitempty"`

	Nombre string `json:"nombre"`

	IdGrado int32 `json:"id_grado"`

	IdSede int32 `json:"id_sede"`

	IdJornada int32 `json:"id_jornada"`
}
