/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorResponseDetails struct {

	Field string `json:"field,omitempty"`

	Message string `json:"message,omitempty"`

	Code string `json:"code,omitempty"`
}
