/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Horario struct {

	IdHorario int32 `json:"id_horario,omitempty"`

	IdCargaAcademica int32 `json:"id_carga_academica"`

	IdDia int32 `json:"id_dia"`

	HoraInicio string `json:"hora_inicio"`

	HoraFin string `json:"hora_fin"`
}
