/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Jornada struct {

	IdJornada int32 `json:"id_jornada,omitempty"`

	Nombre string `json:"nombre"`
}
