/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Estudiante struct {

	DocumentoIdentidad string `json:"documento_identidad"`

	TipoDocumento string `json:"tipo_documento"`
	// Debe ser una fecha pasada
	FechaNacimiento string `json:"fecha_nacimiento,omitempty"`

	Telefono string `json:"telefono,omitempty"`

	CorreoElectronico string `json:"correo_electronico,omitempty"`

	IdEstudiante int32 `json:"id_estudiante,omitempty"`

	Nombres string `json:"nombres"`

	Apellidos string `json:"apellidos"`

	Direccion string `json:"direccion,omitempty"`

	IdMunicipio int32 `json:"id_municipio,omitempty"`
}
