/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AnioLectivo struct {

	IdAnioLectivo int32 `json:"id_anio_lectivo,omitempty"`

	Anio int32 `json:"anio"`

	FechaInicio string `json:"fecha_inicio"`

	FechaFin string `json:"fecha_fin"`

	Estado string `json:"estado,omitempty"`
}
