/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Docente struct {

	IdDocente int32 `json:"id_docente,omitempty"`

	Nombres string `json:"nombres"`

	Apellidos string `json:"apellidos"`

	DocumentoIdentidad string `json:"documento_identidad"`

	TipoDocumento string `json:"tipo_documento"`

	Profesion string `json:"profesion,omitempty"`

	Telefono string `json:"telefono,omitempty"`

	CorreoElectronico string `json:"correo_electronico,omitempty"`
}
