/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Sede struct {

	IdSede int32 `json:"id_sede,omitempty"`

	Nombre string `json:"nombre"`

	Direccion string `json:"direccion,omitempty"`

	IdInstitucion int32 `json:"id_institucion"`

	IdMunicipio int32 `json:"id_municipio,omitempty"`
}
