/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorResponse struct {

	Error_ string `json:"error,omitempty"`

	Message string `json:"message,omitempty"`

	Details []ErrorResponseDetails `json:"details,omitempty"`
}
