/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Usuario struct {

	IdUsuario int32 `json:"id_usuario,omitempty"`

	NombreUsuario string `json:"nombre_usuario"`

	Clave string `json:"clave"`

	IdDocente int32 `json:"id_docente,omitempty"`

	IdEstudiante int32 `json:"id_estudiante,omitempty"`

	Activo bool `json:"activo,omitempty"`

	IdRol int32 `json:"id_rol,omitempty"`
}
