/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Institucion struct {

	IdInstitucion int32 `json:"id_institucion,omitempty"`

	Nombre string `json:"nombre"`

	CodigoDane string `json:"codigo_dane"`
}
