/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TipoEvaluacion struct {

	IdTipoEvaluacion int32 `json:"id_tipo_evaluacion,omitempty"`

	Nombre string `json:"nombre"`

	Descripcion string `json:"descripcion,omitempty"`
}
