/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DiaSemana struct {

	IdDia int32 `json:"id_dia,omitempty"`

	Nombre string `json:"nombre"`

	Codigo int32 `json:"codigo"`
}
