/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Matricula struct {

	IdMatricula int32 `json:"id_matricula,omitempty"`

	IdEstudiante int32 `json:"id_estudiante"`

	IdGrupo int32 `json:"id_grupo"`

	IdAnioLectivo int32 `json:"id_anio_lectivo"`

	FechaMatricula string `json:"fecha_matricula,omitempty"`

	Estado string `json:"estado,omitempty"`
}
