/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Calificacion struct {

	IdCalificacion int32 `json:"id_calificacion,omitempty"`

	IdEvaluacion int32 `json:"id_evaluacion"`

	IdMatricula int32 `json:"id_matricula"`

	Nota float32 `json:"nota"`

	Observaciones string `json:"observaciones,omitempty"`

	FechaCalificacion time.Time `json:"fecha_calificacion,omitempty"`
}
