/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2004 struct {

	Data []Jornada `json:"data,omitempty"`

	Pagination *InlineResponse2004Pagination `json:"pagination,omitempty"`
}
