/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RespuestaEstudiante struct {

	IdRespuesta int32 `json:"id_respuesta,omitempty"`

	IdPregunta int32 `json:"id_pregunta"`

	IdCalificacion int32 `json:"id_calificacion"`

	Respuesta string `json:"respuesta,omitempty"`

	PuntajeObtenido float32 `json:"puntaje_obtenido,omitempty"`

	IdOpcionSeleccionada int32 `json:"id_opcion_seleccionada,omitempty"`
}
