/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Pregunta struct {

	IdPregunta int32 `json:"id_pregunta,omitempty"`

	IdEvaluacion int32 `json:"id_evaluacion"`

	Enunciado string `json:"enunciado"`

	Tipo string `json:"tipo"`

	Peso float32 `json:"peso,omitempty"`
}
