/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ActividadRecuperacion struct {

	IdRecuperacion int32 `json:"id_recuperacion,omitempty"`

	IdCalificacion int32 `json:"id_calificacion"`

	Fecha string `json:"fecha"`

	Descripcion string `json:"descripcion"`

	NotaRecuperacion float32 `json:"nota_recuperacion,omitempty"`

	FechaCalificacion time.Time `json:"fecha_calificacion,omitempty"`
}
