/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Periodo struct {

	IdPeriodo int32 `json:"id_periodo,omitempty"`

	Nombre string `json:"nombre"`

	FechaInicio string `json:"fecha_inicio"`

	FechaFin string `json:"fecha_fin"`

	IdAnioLectivo int32 `json:"id_anio_lectivo"`
}
