/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Logro struct {

	IdLogro int32 `json:"id_logro,omitempty"`

	Descripcion string `json:"descripcion"`

	IdCompetencia int32 `json:"id_competencia"`

	IdPeriodo int32 `json:"id_periodo"`

	Porcentaje float32 `json:"porcentaje,omitempty"`
}
