/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse20021 struct {

	AccessToken string `json:"access_token,omitempty"`

	TokenType string `json:"token_type,omitempty"`
}
