/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CargaAcademica struct {

	IdCarga int32 `json:"id_carga,omitempty"`

	IdDocente int32 `json:"id_docente"`

	IdGrupo int32 `json:"id_grupo"`

	IdAsignatura int32 `json:"id_asignatura"`

	IdAnioLectivo int32 `json:"id_anio_lectivo"`
}
