/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OpcionRespuesta struct {

	IdOpcion int32 `json:"id_opcion,omitempty"`

	IdPregunta int32 `json:"id_pregunta"`

	Texto string `json:"texto"`

	EsCorrecta bool `json:"es_correcta,omitempty"`
}
