/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EstudianteAcudiente struct {

	IdEstudiante int32 `json:"id_estudiante"`

	IdAcudiente int32 `json:"id_acudiente"`

	Parentesco string `json:"parentesco,omitempty"`

	EsPrincipal bool `json:"es_principal,omitempty"`
}
