/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Competencia struct {

	IdCompetencia int32 `json:"id_competencia,omitempty"`

	Nombre string `json:"nombre"`

	Descripcion string `json:"descripcion,omitempty"`

	IdAsignatura int32 `json:"id_asignatura"`

	IdGrado int32 `json:"id_grado"`
}
