/*
 * API Instituciones Educativas Colombia
 *
 * API para gestión de instituciones educativas públicas en Colombia
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/edalmava-030/sia/1.0.0/",
		Index,
	},

	Route{
		"AcudientesGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/acudientes",
		AcudientesGet,
	},

	Route{
		"AcudientesIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/acudientes/{id}",
		AcudientesIdDelete,
	},

	Route{
		"AcudientesIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/acudientes/{id}",
		AcudientesIdGet,
	},

	Route{
		"AcudientesIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/acudientes/{id}",
		AcudientesIdPut,
	},

	Route{
		"AcudientesPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/acudientes",
		AcudientesPost,
	},

	Route{
		"AnioLectivoGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/anio-lectivo",
		AnioLectivoGet,
	},

	Route{
		"AnioLectivoIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/anio-lectivo/{id}",
		AnioLectivoIdDelete,
	},

	Route{
		"AnioLectivoIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/anio-lectivo/{id}",
		AnioLectivoIdGet,
	},

	Route{
		"AnioLectivoIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/anio-lectivo/{id}",
		AnioLectivoIdPut,
	},

	Route{
		"AnioLectivoPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/anio-lectivo",
		AnioLectivoPost,
	},

	Route{
		"AsignaturasGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/asignaturas",
		AsignaturasGet,
	},

	Route{
		"AsignaturasIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/asignaturas/{id}",
		AsignaturasIdDelete,
	},

	Route{
		"AsignaturasIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/asignaturas/{id}",
		AsignaturasIdGet,
	},

	Route{
		"AsignaturasIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/asignaturas/{id}",
		AsignaturasIdPut,
	},

	Route{
		"AsignaturasPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/asignaturas",
		AsignaturasPost,
	},

	Route{
		"AsistenciaGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/asistencia",
		AsistenciaGet,
	},

	Route{
		"AsistenciaIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/asistencia/{id}",
		AsistenciaIdDelete,
	},

	Route{
		"AsistenciaIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/asistencia/{id}",
		AsistenciaIdGet,
	},

	Route{
		"AsistenciaIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/asistencia/{id}",
		AsistenciaIdPut,
	},

	Route{
		"AsistenciaPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/asistencia",
		AsistenciaPost,
	},

	Route{
		"AuthLoginPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/auth/login",
		AuthLoginPost,
	},

	Route{
		"AuthLogoutPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/auth/logout",
		AuthLogoutPost,
	},

	Route{
		"AuthRefreshPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/auth/refresh",
		AuthRefreshPost,
	},

	Route{
		"CalificacionesGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/calificaciones",
		CalificacionesGet,
	},

	Route{
		"CalificacionesIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/calificaciones/{id}",
		CalificacionesIdDelete,
	},

	Route{
		"CalificacionesIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/calificaciones/{id}",
		CalificacionesIdGet,
	},

	Route{
		"CalificacionesIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/calificaciones/{id}",
		CalificacionesIdPut,
	},

	Route{
		"CalificacionesPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/calificaciones",
		CalificacionesPost,
	},

	Route{
		"CargaAcademicaGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/carga-academica",
		CargaAcademicaGet,
	},

	Route{
		"CargaAcademicaIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/carga-academica/{id}",
		CargaAcademicaIdDelete,
	},

	Route{
		"CargaAcademicaIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/carga-academica/{id}",
		CargaAcademicaIdGet,
	},

	Route{
		"CargaAcademicaIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/carga-academica/{id}",
		CargaAcademicaIdPut,
	},

	Route{
		"CargaAcademicaPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/carga-academica",
		CargaAcademicaPost,
	},

	Route{
		"CompetenciasGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/competencias",
		CompetenciasGet,
	},

	Route{
		"CompetenciasIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/competencias/{id}",
		CompetenciasIdDelete,
	},

	Route{
		"CompetenciasIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/competencias/{id}",
		CompetenciasIdGet,
	},

	Route{
		"CompetenciasIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/competencias/{id}",
		CompetenciasIdPut,
	},

	Route{
		"CompetenciasPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/competencias",
		CompetenciasPost,
	},

	Route{
		"DocentesGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/docentes",
		DocentesGet,
	},

	Route{
		"DocentesIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/docentes/{id}",
		DocentesIdDelete,
	},

	Route{
		"DocentesIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/docentes/{id}",
		DocentesIdGet,
	},

	Route{
		"DocentesIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/docentes/{id}",
		DocentesIdPut,
	},

	Route{
		"DocentesPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/docentes",
		DocentesPost,
	},

	Route{
		"EstudiantesGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/estudiantes",
		EstudiantesGet,
	},

	Route{
		"EstudiantesIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/estudiantes/{id}",
		EstudiantesIdDelete,
	},

	Route{
		"EstudiantesIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/estudiantes/{id}",
		EstudiantesIdGet,
	},

	Route{
		"EstudiantesIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/estudiantes/{id}",
		EstudiantesIdPut,
	},

	Route{
		"EstudiantesPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/estudiantes",
		EstudiantesPost,
	},

	Route{
		"EvaluacionesGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/evaluaciones",
		EvaluacionesGet,
	},

	Route{
		"EvaluacionesIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/evaluaciones/{id}",
		EvaluacionesIdDelete,
	},

	Route{
		"EvaluacionesIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/evaluaciones/{id}",
		EvaluacionesIdGet,
	},

	Route{
		"EvaluacionesIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/evaluaciones/{id}",
		EvaluacionesIdPut,
	},

	Route{
		"EvaluacionesPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/evaluaciones",
		EvaluacionesPost,
	},

	Route{
		"GradosGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/grados",
		GradosGet,
	},

	Route{
		"GradosIdAsignaturasGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/grados/{id}/asignaturas",
		GradosIdAsignaturasGet,
	},

	Route{
		"GradosIdAsignaturasPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/grados/{id}/asignaturas",
		GradosIdAsignaturasPost,
	},

	Route{
		"GradosIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/grados/{id}",
		GradosIdDelete,
	},

	Route{
		"GradosIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/grados/{id}",
		GradosIdGet,
	},

	Route{
		"GradosIdGradoAsignaturasIdAsignaturaDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/grados/{id_grado}/asignaturas/{id_asignatura}",
		GradosIdGradoAsignaturasIdAsignaturaDelete,
	},

	Route{
		"GradosIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/grados/{id}",
		GradosIdPut,
	},

	Route{
		"GradosPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/grados",
		GradosPost,
	},

	Route{
		"GruposGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/grupos",
		GruposGet,
	},

	Route{
		"GruposIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/grupos/{id}",
		GruposIdDelete,
	},

	Route{
		"GruposIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/grupos/{id}",
		GruposIdGet,
	},

	Route{
		"GruposIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/grupos/{id}",
		GruposIdPut,
	},

	Route{
		"GruposPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/grupos",
		GruposPost,
	},

	Route{
		"HorariosGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/horarios",
		HorariosGet,
	},

	Route{
		"HorariosIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/horarios/{id}",
		HorariosIdDelete,
	},

	Route{
		"HorariosIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/horarios/{id}",
		HorariosIdGet,
	},

	Route{
		"HorariosIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/horarios/{id}",
		HorariosIdPut,
	},

	Route{
		"HorariosPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/horarios",
		HorariosPost,
	},

	Route{
		"InstitucionesGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/instituciones",
		InstitucionesGet,
	},

	Route{
		"InstitucionesIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/instituciones/{id}",
		InstitucionesIdDelete,
	},

	Route{
		"InstitucionesIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/instituciones/{id}",
		InstitucionesIdGet,
	},

	Route{
		"InstitucionesIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/instituciones/{id}",
		InstitucionesIdPut,
	},

	Route{
		"InstitucionesPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/instituciones",
		InstitucionesPost,
	},

	Route{
		"JornadasGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/jornadas",
		JornadasGet,
	},

	Route{
		"JornadasIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/jornadas/{id}",
		JornadasIdDelete,
	},

	Route{
		"JornadasIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/jornadas/{id}",
		JornadasIdGet,
	},

	Route{
		"JornadasIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/jornadas/{id}",
		JornadasIdPut,
	},

	Route{
		"JornadasPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/jornadas",
		JornadasPost,
	},

	Route{
		"LogrosGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/logros",
		LogrosGet,
	},

	Route{
		"LogrosIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/logros/{id}",
		LogrosIdDelete,
	},

	Route{
		"LogrosIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/logros/{id}",
		LogrosIdGet,
	},

	Route{
		"LogrosIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/logros/{id}",
		LogrosIdPut,
	},

	Route{
		"LogrosPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/logros",
		LogrosPost,
	},

	Route{
		"MatriculasGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/matriculas",
		MatriculasGet,
	},

	Route{
		"MatriculasIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/matriculas/{id}",
		MatriculasIdDelete,
	},

	Route{
		"MatriculasIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/matriculas/{id}",
		MatriculasIdGet,
	},

	Route{
		"MatriculasIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/matriculas/{id}",
		MatriculasIdPut,
	},

	Route{
		"MatriculasPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/matriculas",
		MatriculasPost,
	},

	Route{
		"ObservacionesGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/observaciones",
		ObservacionesGet,
	},

	Route{
		"ObservacionesIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/observaciones/{id}",
		ObservacionesIdDelete,
	},

	Route{
		"ObservacionesIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/observaciones/{id}",
		ObservacionesIdGet,
	},

	Route{
		"ObservacionesIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/observaciones/{id}",
		ObservacionesIdPut,
	},

	Route{
		"ObservacionesPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/observaciones",
		ObservacionesPost,
	},

	Route{
		"PeriodosGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/periodos",
		PeriodosGet,
	},

	Route{
		"PeriodosIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/periodos/{id}",
		PeriodosIdDelete,
	},

	Route{
		"PeriodosIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/periodos/{id}",
		PeriodosIdGet,
	},

	Route{
		"PeriodosIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/periodos/{id}",
		PeriodosIdPut,
	},

	Route{
		"PeriodosPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/periodos",
		PeriodosPost,
	},

	Route{
		"SedesGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/sedes",
		SedesGet,
	},

	Route{
		"SedesIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/sedes/{id}",
		SedesIdDelete,
	},

	Route{
		"SedesIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/sedes/{id}",
		SedesIdGet,
	},

	Route{
		"SedesIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/sedes/{id}",
		SedesIdPut,
	},

	Route{
		"SedesPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/sedes",
		SedesPost,
	},

	Route{
		"UsuariosGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/usuarios",
		UsuariosGet,
	},

	Route{
		"UsuariosIdDelete",
		strings.ToUpper("Delete"),
		"/edalmava-030/sia/1.0.0/usuarios/{id}",
		UsuariosIdDelete,
	},

	Route{
		"UsuariosIdGet",
		strings.ToUpper("Get"),
		"/edalmava-030/sia/1.0.0/usuarios/{id}",
		UsuariosIdGet,
	},

	Route{
		"UsuariosIdPut",
		strings.ToUpper("Put"),
		"/edalmava-030/sia/1.0.0/usuarios/{id}",
		UsuariosIdPut,
	},

	Route{
		"UsuariosPost",
		strings.ToUpper("Post"),
		"/edalmava-030/sia/1.0.0/usuarios",
		UsuariosPost,
	},
}
