# Generated by Django 5.2.1 on 2025-05-10 02:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado'), ('PLANEACION', 'Planeación')], default='ACTIVO', max_length=20)),
            ],
            options={
                'verbose_name': 'Año Lectivo',
                'verbose_name_plural': 'Años Lectivos',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('intensidad_horaria', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('codigo', models.SmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Día de la Semana',
                'verbose_name_plural': 'Días de la Semana',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_dane', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['nombre'],
                'permissions': [('can_access', 'Puede acceder al módulo'), ('can_create', 'Puede crear registros'), ('can_read', 'Puede leer registros'), ('can_update', 'Puede actualizar registros'), ('can_delete', 'Puede eliminar registros')],
            },
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Evaluación',
                'verbose_name_plural': 'Tipos de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='academico.asignatura')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='academico.grado')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academico.grado')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academico.jornada')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='CargaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='academico.aniolectivo')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='academico.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='academico.docente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_academicas', to='academico.grupo')),
            ],
            options={
                'verbose_name': 'Carga Académica',
                'verbose_name_plural': 'Cargas Académicas',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='academico.competencia')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_presentacion', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academico.cargaacademica')),
                ('logro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academico.logro')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DESERTOR', 'Desertor'), ('PROMOVIDO', 'Promovido'), ('RETIRADO', 'Retirado'), ('GRADUADO', 'Graduado')], default='ACTIVO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.aniolectivo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.grupo')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_calificacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.evaluacion')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.matricula')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=5)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='academico.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'unique_together': {('codigo', 'departamento')},
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='academico.municipio'),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='academico.aniolectivo')),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
            },
        ),
        migrations.AddField(
            model_name='logro',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='academico.periodo'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academico.periodo'),
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='academico.modulo')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['modulo', 'nombre'],
                'permissions': [('can_access', 'Puede acceder al permiso'), ('can_create', 'Puede crear registros'), ('can_read', 'Puede leer registros'), ('can_update', 'Puede actualizar registros'), ('can_delete', 'Puede eliminar registros')],
                'unique_together': {('nombre', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('ABIERTA', 'Abierta'), ('OPCION_MULTIPLE', 'Opción Múltiple'), ('VERDADERO_FALSO', 'Verdadero o Falso')], max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='academico.evaluacion')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='academico.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
            },
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, max_length=1000, null=True)),
                ('puntaje_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='academico.calificacion')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecciones', to='academico.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='academico.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Estudiante',
                'verbose_name_plural': 'Respuestas de Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('permisos', models.ManyToManyField(related_name='roles', to='academico.permiso')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
                'permissions': [('can_access', 'Puede acceder al rol'), ('can_create', 'Puede crear registros'), ('can_read', 'Puede leer registros'), ('can_update', 'Puede actualizar registros'), ('can_delete', 'Puede eliminar registros')],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='academico.institucion')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sedes', to='academico.municipio')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='academico.sede'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academico.tipoevaluacion'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='academico.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
                'permissions': [('can_access', 'Puede acceder al usuario'), ('can_create', 'Puede crear registros'), ('can_read', 'Puede leer registros'), ('can_update', 'Puede actualizar registros'), ('can_delete', 'Puede eliminar registros')],
            },
        ),
        migrations.CreateModel(
            name='ObservacionComportamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('tipo_observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('acciones_tomadas', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('carga_academica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to='academico.cargaacademica')),
                ('docente_observador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_realizadas', to='academico.docente')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='academico.matricula')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_creadas', to='academico.usuario')),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_modificadas', to='academico.usuario')),
            ],
            options={
                'verbose_name': 'Observación de Comportamiento',
                'verbose_name_plural': 'Observaciones de Comportamiento',
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_creadas', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='usuario_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_modificadas', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='logro',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logros_creados', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='logro',
            name='usuario_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logros_modificados', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_creadas', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='usuario_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_modificadas', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_creados', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='usuario_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_modificados', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes_creados', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes_modificados', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_academicas_creadas', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='cargaacademica',
            name='usuario_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_academicas_modificadas', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_creadas', to='academico.usuario'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='usuario_modificacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_modificadas', to='academico.usuario'),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_subidos', to='academico.usuario')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['fecha_subida'],
                'permissions': [('can_access', 'Puede acceder al archivo'), ('can_create', 'Puede crear registros'), ('can_read', 'Puede leer registros'), ('can_update', 'Puede actualizar registros'), ('can_delete', 'Puede eliminar registros')],
            },
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acudientes_creados', to='academico.usuario')),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acudientes_modificados', to='academico.usuario')),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'unique_together': {('documento_identidad', 'tipo_documento')},
            },
        ),
        migrations.CreateModel(
            name='ActividadRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nota_recuperacion', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('fecha_calificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperaciones', to='academico.calificacion')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperaciones_creadas', to='academico.usuario')),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recuperaciones_modificadas', to='academico.usuario')),
            ],
            options={
                'verbose_name': 'Actividad de Recuperación',
                'verbose_name_plural': 'Actividades de Recuperación',
            },
        ),
        migrations.CreateModel(
            name='EstudianteAcudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='academico.acudiente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acudientes', to='academico.estudiante')),
            ],
            options={
                'verbose_name': 'Relación Estudiante-Acudiente',
                'verbose_name_plural': 'Relaciones Estudiante-Acudiente',
                'unique_together': {('estudiante', 'acudiente')},
            },
        ),
        migrations.CreateModel(
            name='GradoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='academico.asignatura')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='academico.grado')),
            ],
            options={
                'verbose_name': 'Asignatura por Grado',
                'verbose_name_plural': 'Asignaturas por Grado',
                'unique_together': {('grado', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('carga_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.cargaacademica')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academico.diasemana')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'unique_together': {('carga_academica', 'dia', 'hora_inicio')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('nombre', 'grado', 'sede', 'jornada')},
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudiante', 'grupo', 'anio_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='estudiante',
            unique_together={('documento_identidad', 'tipo_documento')},
        ),
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together={('documento_identidad', 'tipo_documento')},
        ),
        migrations.AlterUniqueTogether(
            name='cargaacademica',
            unique_together={('docente', 'grupo', 'asignatura', 'anio_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('evaluacion', 'matricula')},
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('TARDE', 'Tarde'), ('JUSTIFICADO', 'Justificado')], max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.matricula')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_creadas', to='academico.usuario')),
                ('usuario_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_modificadas', to='academico.usuario')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('matricula', 'fecha')},
            },
        ),
    ]
